[supervisord]
nodaemon=true ;
pidfile=/var/run/supervisord.pid
minfds=10000

[program:php-fpm]
command=php-fpm -F
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0

[program:hajimaripartner_eta-worker]
process_name=hajimaripartner_eta
directory=/var/www
command=php artisan horizon
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
topwaitsecs=3600
